### ISSUE TITLE
Swift formatting

### ISSUE THREAD

**Issue by massimobio** [celanajaya/AdjustableTextField#7]
Not sure if you use some formatting tool but I have been using this:
https://github.com/nicklockwood/SwiftFormat

It's really nice. It has a Xcode plugin that I mapped to a key combo for ease of use.

It formats everything from removing empty multiple lines to correctly formatting space around parameter in functions. Highly recommended 👍

I would also help reducing noice in the diffs when doing pull requests because it would enforce us to use the same formatting.

**Comment by celanajaya** [comment]
Yes, I have this! Since I've been coding on my own so much, I've been pretty lazy about using it.
